import { Preset } from './types';

export const presets: Record<string, Preset> = {
  campfire: {
    name: 'Campfire',
    config: {
      count: 100,
      size: 20,
      sizeVariation: 10,
      lifetime: 2.0,
      lifetimeVariation: 0.5,
      speed: 80,
      speedVariation: 30,
      spread: Math.PI / 6,
      gravity: -50,
      color: '#ff6600',
      opacity: 0.8,
      blendMode: 'lighter',
      emissionRate: 50,
      rotation: 0,
      rotationSpeed: 1,
      fadeIn: 0.2,
      fadeOut: 0.3,
      scaleOverLife: true,
      alphaOverLife: true,
    },
  },
  laser: {
    name: 'Laser',
    config: {
      count: 200,
      size: 8,
      sizeVariation: 3,
      lifetime: 0.5,
      lifetimeVariation: 0.2,
      speed: 400,
      speedVariation: 50,
      spread: Math.PI / 24,
      gravity: 0,
      color: '#00ffff',
      opacity: 1.0,
      blendMode: 'lighter',
      emissionRate: 200,
      rotation: 0,
      rotationSpeed: 0,
      fadeIn: 0.1,
      fadeOut: 0.8,
      scaleOverLife: false,
      alphaOverLife: true,
    },
  },
  dust: {
    name: 'Dust',
    config: {
      count: 150,
      size: 4,
      sizeVariation: 2,
      lifetime: 3.0,
      lifetimeVariation: 1.0,
      speed: 20,
      speedVariation: 10,
      spread: Math.PI,
      gravity: 10,
      color: '#cccccc',
      opacity: 0.4,
      blendMode: 'source-over',
      emissionRate: 30,
      rotation: 0,
      rotationSpeed: 2,
      fadeIn: 0.3,
      fadeOut: 0.4,
      scaleOverLife: false,
      alphaOverLife: true,
    },
  },
  water: {
    name: 'Water',
    config: {
      count: 80,
      size: 15,
      sizeVariation: 5,
      lifetime: 1.5,
      lifetimeVariation: 0.3,
      speed: 150,
      speedVariation: 50,
      spread: Math.PI / 4,
      gravity: 200,
      color: '#4488ff',
      opacity: 0.7,
      blendMode: 'source-over',
      emissionRate: 40,
      rotation: 0,
      rotationSpeed: 3,
      fadeIn: 0.1,
      fadeOut: 0.2,
      scaleOverLife: true,
      alphaOverLife: true,
    },
  },
};
